version: '3.6'
services:
  # API esrver
  dialogue-api:
    container_name: dialogue-api
    environment:
      TZ: "Asia/Tokyo"
      ENV: production
      GOOGLE_APPLICATION_CREDENTIALS: /app/restaurant-chatbot-252908-2981cc9b5b05.json
    volumes:
      - ./app:/app/
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/app/restaurant-chatbot-252908-2981cc9b5b05.json:ro
    ports:
      - 5231:5231
    build:
      context: ./app
      dockerfile: Dockerfile
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--debug", "--port", "5231", "--reload-dir", "/app"]
    stdin_open: true
    tty: true

  dialogue-ssl:
    container_name: dialogue-ssl
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - dialogue-api
    restart: always
    environment:
      DOMAINS: 'www.restaurant-concierge.net -> http://dialogue-api:5231'
      # DOMAINS: 'www.restaurant-concierge.net'
      STAGE: 'staging' # Don't use production until staging works
      # FORCE_RENEW: 'true'
